# Generated by Django 5.1.2 on 2024-11-03 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=200)),
                ('arquivo', models.FileField(upload_to='pdfs/')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios', to='lcc_app.materias')),
            ],
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=200)),
                ('arquivo', models.FileField(upload_to='pdfs/')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='lcc_app.materias')),
            ],
        ),
    ]
